name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect project directory
        run: |
          if [ -f "phaserider/CMakeLists.txt" ]; then
            echo "PROJECT_DIR=phaserider" >> $GITHUB_ENV
          else
            echo "PROJECT_DIR=." >> $GITHUB_ENV
          fi

      - name: Configure
        run: cmake -S . -B build
        working-directory: ${{ env.PROJECT_DIR }}

      - name: Build
        run: cmake --build build -j
        working-directory: ${{ env.PROJECT_DIR }}
